version: "3"

services:
  postgresDB:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: users
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      PGDATA: \PostgresStorage\data\pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:\PostgresStorage\data\pgdata

volumes:
  db-data:
